### PR TITLE
Boot messages & inferred script name printing

### LINKED ISSUE #217: Refine prints when crow is booted / restarted
Currently when crow restarts there are a bunch of prints as each library is successfully loaded in the Lua environment. These are pretty much always the same & I've never seen them fail apart from a bogus firmware. Consider that if anything they should be 'debug' prints that aren't in the release version of the firmware.

Instead, does it make sense to print something when crow is booted, or after `^^k`, or after a new program is run/uploaded with `^^s` and `^^w/e`? This could be similar to `^^p` where it can say:
1. 'First' running
2. No user script running
3. User script running

If we wanted to get fancy, the user script could print the first line of the uploaded file (if it's a comment with three dashes) as this is likely the name of the script.

### PR DESCRIPTION
**Pull request by trentgill**
When running `^^c` and `^^F` the successful change is confirmed to the user.

When running / uploading with `druid`, adds confirmation of a successful flash (if ending with `^^w`). Then print `Running: <script name>` where `<script name>` is the first line of the uploaded script, after the comments & any spaces. We can't enforce this, but I think when people see the name of their script appear, they'll want that (and i'll add it to the scripting docs).

Fixes #217.

### CODE REVIEW

File: lib/flash.c [hunk 1]
```diff
@@ -125,6 +123,39 @@ uint8_t Flash_read_user_script( char* buffer )
...
+    }
+    return dest;
+}
+
+char* Flash_script_name( void )
+{
+    static char script[32];
+    memset( script, '\0', 32 );
+    switch( Flash_which_user_script() ){
+        case USERSCRIPT_Clear: strcpy( script, "User script cleared. Running." ); break;
```
Comment (simonvanderveldt) [inline lib/flash.c]: This is the case when there is no script?
If so wouldn't something like "No user script" be a clearer message? The "Running" at the end here is throwing me off, what is it running if there's no script?

And it seems these messages duplicate the ones here https://github.com/monome/crow/pull/227/files#diff-4c329923d1fdc04b8b83730be099f7dfR119
Could we merge them/the logic somehow?

Comment (trentgill) [reply lib/flash.c]: I agree it'd be nice to merge the logic.

Originally I had the same "No user script" message, but it's strange because it's what you see immediately after typing `^^c`, so it feels really strange. To me, responding to a user command with "No user script" *feels* like an error message, rather than confirmation of what the user just performed. I agree re: 'running'. will remove.

At present, the printing on boot isn't even working for some reason (an existing issue i had forgotten), so for now they are better described as the messages you see after changing what the user script is.

**Comment by trentgill** [comment]
On restart, unfortunately the prints aren't working for some reason. Only prints from Lua were coming out before the init() function was called which I can't (right now) explain.

I opted for the "use the top-line comment" because 1) it's way easier to implement, 2) doesn't break druid, 3) is familiar to norns scripters as that's how the on-board script-docs are generated.

Perhaps i'm being lazy, but it feels elegant & logical that the first line in your script would be the name of the script.

File: lib/flash.c (hunk 1 above)
Comment (simonvanderveldt) [reply lib/flash.c]: Re: `^^c` I guess the only place/moment we can confirm to the user that the script has been cleared is immediately after clearing it (I guess that would be in `Flash_clear_user_script`).

I guess we could even omit passing the script name to `Lua_crowbegin` in that case?

Comment (trentgill) [reply lib/flash.c]: Updated the PR to consolidate the logic for 'print' and 'which script'.

**Comment by trentgill** [comment]
Restructured a few things to cleanup main.c and flash.c. all the flash-touching commands happen via the repl library as they are alt versions of the 'upload' procedure.

File: lib/repl.c [hunk 2]
```diff
@@ -76,21 +77,44 @@ void REPL_upload( int flash )
...
+    Caw_send_luachunk("User script cleared.");
+    REPL_print_script_name(NULL);
+    Lua_crowbegin();
+}
+
+void REPL_default_script( void )
+{
+    Lua_Reset();
+    Flash_default_user_script();
+    Caw_send_luachunk("Using default script.");
```
Comment (simonvanderveldt) [inline lib/repl.c]: Seems like we're using both "default" and "First" for this. Should we just use "First" here for clarity?

**Comment by tehn** [comment]
looks good

File: lib/repl.c (hunk 2 above)
Comment (trentgill) [reply lib/repl.c]: I'm going to leave it because it is *always* followed by `"Running: First.lua"`. Folks seem to have a hard time with whether 'First' is getting replaced when they upload a script, so calling it the `default` script I think helps with seeing it as 3rd category.
